apiVersion: v1
kind: Service
metadata:
  name: {{ include "video-downloader.fullname" . }}
  labels:
    {{- include "video-downloader.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    {{- if .Values.nginx.enabled }}
    - port: {{ .Values.nginx.servicePort }}
      targetPort: {{ .Values.nginx.port }}
      protocol: TCP
      name: nginx
    {{- end }}
  selector:
    {{- include "video-downloader.selectorLabels" . | nindent 4 }}
