{{- if .Values.customConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql.fullname" . }}-config
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
data:
  custom.cnf: |
{{ .Values.customConfig | indent 4 }}
{{- end }}
