{{- if .Values.customConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}-config
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
  postgresql.conf: |
{{ .Values.customConfig | indent 4 }}
{{- end }}
